export function GET() {
  return new Response(
    [
      "# brw",
      "",
      "brw — complete Chrome and Chromium control for agents, fast by default and repeatable by recipe.",
      "",
      "- Site: https://brw.donworks.co.uk",
      "- Source: https://github.com/Don-Works/brw",
      "- Umbrella: https://donworks.co.uk (Don Works, open source by Revitt)",
      "- Siblings: https://github.com/Don-Works/mcplexer, https://github.com/Don-Works/resident, https://github.com/Don-Works/handler",
      "- Parent: https://revitt.co",
      "- Licence: AGPL-3.0",
      "",
      "## What it is",
      "",
      "brw runs a real, visible Chrome/Chromium browser and exposes it over MCP (stdio) and an HTTP JSON API. Agents inspect semantic controls as stable refs like `e17`, act by ref, and receive a focused post-action observation. Multi-step work can run as a batch or plan; proven work can be installed as a private, deterministic recipe and reused with search + run.",
      "",
      "## Features",
      "",
      "- Controls headed Chrome/Chromium through direct CDP or an installed-profile extension bridge.",
      "- Cross-harness: stdio MCP tools for agent harnesses plus an HTTP JSON API for custom clients.",
      "- SSH-first remote runtime: the visible browser and its profile stay on the machine that owns them; SSH carries stdio MCP.",
      "- Installed-Chrome profile bridge via a Chrome extension for auth that already exists in an installed profile.",
      "- Semantic snapshot/read/find: DOM + accessibility data, prose, links, headings, forms, tables, structured product data.",
      "- Acts by ref: click, type, fill, select, press, scroll, hover, drag, upload, commit, wait and assert.",
      "- Returns a post-action observation instead of requiring a confirmation screenshot or re-snapshot.",
      "- Batch, plan, cancellation, cheap change observation and trace-to-replay for multi-step work.",
      "- Private deterministic recipes: metadata-only semantic search, immutable id/version/digest pinning, exact origins, declared risk, timers, page/browser events, idempotency and postconditions.",
      "- Tabs, tab leases and tab groups; background opens do not steal OS focus.",
      "- Downloads, console, network resources/capture, guarded in-page request replay and WebMCP page tools.",
      "- Screenshots and element crops as visual fallback, with optional Set-of-Marks overlays.",
      "- Browser-host artifacts for text, semantic JSON, screenshots, PDFs, downloads and bounded video; search/read by opaque handle.",
      "- Responsive device emulation, real window resizing/bounds and desktop notifications for human hand-off.",
      "- Fresh incognito contexts and HttpOnly cookie controls on dedicated direct-CDP profiles. The installed-profile extension deliberately blocks cookie and bulk-storage CDP methods.",
      "- An on-demand MCP catalogue starts with 13 tools instead of advertising all 62 on every turn.",
      "",
      "## Recipes",
      "",
      "Known workflows take two model-facing calls: `brw_recipe_search { query, origin }`, then `brw_recipe_run { id, version, digest, inputs }`. Recipe bodies remain in an owner-controlled private directory or HTTPS provider. They are schema-validated, immutable, origin-scoped and risk-aware; they are browser mechanics, not standing authorization for an external write.",
      "",
      "## Performance evidence",
      "",
      "Reproducible local probes on an Apple M4 Max in September 2026 measured 2.31x faster pre-armed event settling, 51.9x less transfer for a bounded proxied read, a 6,332x smaller model-facing result for a 1.31 MB browser-host artifact, and 69.9% less initial tool-catalogue context in auto mode than advertising all tools. These are brw engineering probes, not Claude measurements. Private pre-release comparisons with Claude in Chrome were directionally better on turns, tokens, wall time and estimated cost; raw transcripts are not public, so brw does not present numeric Claude head-to-head claims.",
      "",
      "## Install",
      "",
      "One command on macOS and Linux. It installs under the user's home directory, needs no administrator rights, and hands off to `brwctl setup`, which starts the bridge daemon in the background, registers brw with the MCP client and installs the agent skill:",
      "",
      "  curl -fsSL https://brw.donworks.co.uk/install.sh | sh",
      "",
      "The script is readable at https://brw.donworks.co.uk/install.sh before it is run.",
      "",
      "Other routes, in order of preference: `brew install don-works/tap/brw` then `brwctl setup`; the macOS .pkg for admin/MDM installs; Linux .deb/.rpm; the Windows .msi. All are on https://github.com/Don-Works/brw/releases.",
      "",
      "Connecting a browser is the remaining step. Chromium force-installs the extension from a single policy file pointed at the self-hosted CRX and update manifest. Chrome uses load-unpacked today; a Chrome Web Store build is being prepared for review and no listing exists yet. Either way the extension stays disconnected until the user clicks Enable local browser control in its Options page. Extension id: amocjcgddnoakjijfggdpnefdnboilpe.",
      "",
      "Run the daemon directly if you prefer:",
      "",
      "  brwd --mcp --http off",
      "",
      "Or expose the HTTP API on loopback:",
      "",
      "  brwd --http 127.0.0.1:17310",
      "",
      "Source build fallback:",
      "",
      "  git clone https://github.com/Don-Works/brw.git",
      "  cd brw",
      "  make build",
      "  ./bin/brwd --mcp --http off",
      "",
      "Run `brwd --mcp --mcp-tools auto` for the lean default that starts at 13 tools and grows on demand. `core` advertises 24 tools and `minimal` advertises 12; all tools remain callable.",
      "",
      "## Transports",
      "",
      "Two lanes, with different capabilities. Extension bridge: drives the user's installed, signed-in Chrome or Chromium; gets Chrome tab groups; has no incognito, no HttpOnly cookie access and no download routing; started with `brwd --bridge`. Direct CDP: drives a separate browser instance on a profile brw owns; gets incognito contexts (`brw_open_incognito`), cookie tools (`brw_cookies`, HttpOnly included), deterministic download staging and headless; started with `brwd --mcp --http off`. The one-line installer sets up the bridge. `brw_identity` reports which transport a namespace is on.",
      "",
      "## Trust and provenance",
      "",
      "- AGPL-3.0; daemon, CLI and extension in one public repository. The extension ships unminified.",
      "- Every release artifact carries a GitHub build-provenance attestation: `gh attestation verify <artifact> --repo Don-Works/brw`.",
      "- Every release carries SHA256SUMS.txt and a CycloneDX SBOM (brw_<version>_sbom.cdx.json).",
      "- macOS Developer ID signing/notarisation and Windows Authenticode signing are landing in the next release; they are not in a published release yet.",
      "- A release tag builds only after unit tests, a real-browser functional suite, go vet, staticcheck, govulncheck and a gitleaks history scan.",
      "- The extension id amocjcgddnoakjijfggdpnefdnboilpe is pinned by the manifest public key and trusted by the daemon with no configuration.",
      "- Extension privacy policy: https://brw.donworks.co.uk/privacy/extension. The extension collects nothing, transmits nothing to Don Works, Revitt or any third party, and reaches only ws://127.0.0.1 on the user's own machine.",
      "",
      "## Safety",
      "",
      "brw uses a normal visible browser and persistent user profile. It does not add stealth code, CAPTCHA bypass, MFA bypass, fraud-check bypass, or consent bypass. The installed-profile extension refuses HttpOnly cookie and bulk-storage CDP methods; explicit cookie tools exist only on dedicated direct-CDP profiles. Browser-control HTTP binds to loopback by default; for remote use, prefer stdio MCP over SSH.",
      "",
      "Released under AGPL-3.0 — free to use, change, and build on, with improvements shared back. If that doesn't fit your business, ask Revitt about a commercial licence.",
    ].join("\n"),
    {
      headers: {
        "content-type": "text/plain; charset=utf-8",
      },
    },
  );
}
