export function GET() {
  return new Response(
    [
      "# brw",
      "",
      "brw — semantic browser control for agents.",
      "",
      "- Site: https://brw.donworks.co.uk",
      "- Source: https://github.com/Don-Works/brw",
      "- Umbrella: https://donworks.co.uk (Don Works, open source by Revitt)",
      "- Siblings: https://github.com/Don-Works/mcplexer, https://github.com/Don-Works/resident, https://github.com/Don-Works/handler",
      "- Parent: https://revitt.co",
      "- Licence: AGPL-3.0",
      "",
      "## What it is",
      "",
      "brw runs a real, visible Chrome/Chromium browser and exposes it over MCP (stdio) and an HTTP JSON API. Agents act on the actual web from stable refs like `e17` instead of CSS selectors or screenshots, and get a post-action observation back after every action so they know what actually happened. Screenshots are a visual fallback only, with optional Set-of-Marks overlays.",
      "",
      "## Features",
      "",
      "- Controls headed Chrome/Chromium through CDP.",
      "- Cross-harness: stdio MCP tools for agent harnesses plus an HTTP JSON API for custom clients.",
      "- SSH-first remote runtime: the visible browser and its profile stay on the machine that owns them; SSH carries stdio MCP.",
      "- Installed-Chrome profile bridge via a Chrome extension for auth that already exists in an installed profile.",
      "- Semantic snapshot/read/find: DOM + accessibility data, prose, links, headings, forms, tables, structured product data.",
      "- Acts by ref: click, type, fill, select, scroll, drag, upload, wait, assert.",
      "- Tabs and tab groups, downloads, console, network capture and request replay, cancellation.",
      "- Set-of-Marks overlays label elements with the same refs the agent acts on.",
      "",
      "## Quick start",
      "",
      "Download a native installer from https://github.com/Don-Works/brw/releases:",
      "",
      "- Windows: .msi",
      "- macOS: .pkg",
      "- Linux: .deb or .rpm",
      "",
      "Then run:",
      "",
      "  brwd --mcp --http off",
      "",
      "Or expose the HTTP API on loopback:",
      "",
      "  brwd --http 127.0.0.1:17310",
      "",
      "Source build fallback:",
      "",
      "  git clone https://github.com/Don-Works/brw.git",
      "  cd brw",
      "  make build",
      "  ./bin/brwd --mcp --http off",
      "",
      "Run `brwd --mcp --mcp-tools core` for a lean agent context that advertises only common-flow tools while keeping all tools callable.",
      "",
      "## Safety",
      "",
      "brw uses a normal visible browser and persistent user profile. It does not add stealth code, CAPTCHA bypass, MFA bypass, fraud-check bypass, consent bypass, or cookie extraction. Browser-control HTTP binds to loopback by default; for remote use, prefer stdio MCP over SSH.",
      "",
      "Released under AGPL-3.0 — free to use, change, and build on, with improvements shared back. If that doesn't fit your business, ask Revitt about a commercial licence.",
    ].join("\n"),
    {
      headers: {
        "content-type": "text/plain; charset=utf-8",
      },
    },
  );
}
