import { comparisonRows, measurements } from "@/lib/siteEvidence";

export function GET() {
  return new Response(
    [
      "# brw",
      "",
      "brw — semantic browser control for your agent, with bounded reads and repeatable recipes.",
      "",
      "- Site: https://brw.donworks.co.uk",
      "- Source: https://github.com/Don-Works/brw",
      "- Umbrella: https://donworks.co.uk (Don Works, open source by Revitt)",
      "- Siblings: https://github.com/Don-Works/resident, https://github.com/Don-Works/handler",
      "- Parent: https://revitt.co",
      "- Licence: AGPL-3.0",
      "",
      "## What it is",
      "",
      "brw runs a real, visible Chromium-based browser (Chrome, Chromium, Edge, Brave, Vivaldi, Opera or Arc) and exposes it over MCP (stdio) and an HTTP JSON API. Agents inspect semantic controls as stable refs like `e17`, act by ref, and receive a focused post-action observation. Multi-step work can run as a batch or plan; proven work can run as a caller-supplied recipe, a reviewed repository file, or a pinned provider recipe.",
      "",
      "## Browser support",
      "",
      "Supported browser family: Chromium. Setup names Chrome, Chromium, Edge, Brave, Vivaldi, Opera and Arc; installation and capabilities depend on browser, OS and transport. Firefox is not supported through normal brw tools: internal/bidi is a research prototype, not a brwd backend. Safari has no supported backend. Findings: https://github.com/Don-Works/brw/blob/main/docs/bidi-prototype.md",
      "",
      "## Models and optional workers",
      "",
      "Your main agent can use brw directly through MCP, HTTP or the CLI. The daemon requires no model service, classifier or Maix. Source-checkout experiments offer a configurable local or hosted generative reading worker and optional classifier for bounded decisions. Use either, both or neither. A worker returns a bounded answer with a source; its input processing still has a cost. A classifier such as Jev selects among supplied candidates; it does not write answers. These experiments are not a released brw_answer MCP tool. Passage selection introduced a factual regression in a small canary and is not enabled by default.",
      "",
      "## Features",
      "",
      "- Controls any headed Chromium browser through direct CDP or an installed-profile extension bridge.",
      "- Cross-harness: stdio MCP tools for agent harnesses plus an HTTP JSON API for custom clients.",
      "- SSH-first remote runtime: the visible browser and its profile stay on the machine that owns them; SSH carries stdio MCP.",
      "- Installed-Chrome profile bridge via a Chrome extension for auth that already exists in an installed profile.",
      "- Semantic snapshot/read/find: DOM + accessibility data, prose, links, headings, forms, tables, structured product data.",
      "- Acts by ref: click, type, fill, select, press, scroll, hover, drag, upload, commit, wait and assert.",
      "- Returns a post-action observation instead of requiring a confirmation screenshot or re-snapshot.",
      "- Batch, plan, cancellation, cheap change observation and trace-to-replay for multi-step work.",
      "- Deterministic recipes: pass a recipe object directly or use metadata-only provider search with immutable id/version/digest pins. Both paths enforce exact origins, declared risk and postconditions.",
      "- Tabs, tab leases and tab groups; background opens do not steal OS focus.",
      "- Uses a site's agent surfaces before its human UI: WebMCP page tools, declared MCP and API endpoints, llms.txt and markdown. See Agent surfaces below.",
      "- Downloads, console, network resources/capture and guarded in-page request replay.",
      "- Screenshots and element crops as visual fallback, with optional Set-of-Marks overlays.",
      "- Browser-host artifacts for text, semantic JSON, screenshots, PDFs, downloads and bounded video; search/read by opaque handle.",
      "- Responsive device emulation, real window resizing/bounds and desktop notifications for human hand-off.",
      "- Fresh incognito contexts and HttpOnly cookie controls on dedicated direct-CDP profiles. The installed-profile extension deliberately blocks cookie and bulk-storage CDP methods.",
      "- An on-demand MCP catalogue starts with 14 tools and discloses more on request.",
      "",
      "## Agent surfaces",
      "",
      "- Page: https://brw.donworks.co.uk/agent-web (markdown: https://brw.donworks.co.uk/agent-web.md)",
      "",
      "Order brw follows: a WebMCP tool on the page, then the site's own MCP server or API called directly, then llms.txt or a markdown copy, then the DOM.",
      "",
      "- `brw_page_tools`, `brw_call_page_tool`, `brw_page_tool_result`, `brw_page_tool_cancel`: list and call the tools a page registers through WebMCP, on every transport including the extension bridge. A native `document.modelContext` is used when present and never shimmed over; `brwd --enable-webmcp` installs a fallback runtime at document start (with `navigator.modelContext` as a legacy alias) for browsers without one. Declarative `<form toolname>` tools are listed. `readOnlyHint` and `consequentialHint` are surfaced, consequential tools go through the confirm-actions gate, and results are marked `untrusted_output`. Tools registered after hydration are waited for (up to 2 s to list, 2.5 s to call, on a young document).",
      "- `brw_open`, `brw_navigate_to` and `brw_navigate` report `page_tools` and `agent_surfaces` for the landed page.",
      "- `brw_read_url`: no tab, no cookies. Negotiates markdown, then reports `agent_surfaces` (llms.txt, .md twins, `<link rel=alternate type=text/markdown>`, RFC 9727 /.well-known/api-catalog, MCP server cards in /.well-known/ai-catalog.json, /.well-known/ucp, A2A agent card; ai-plugin.json as deprecated), `content_signal`, `markdown_tokens` and `fallback_hint` (login_wall, js_shell, challenge, auth_required) when the agent should step up to a real tab. User-Agent: `brw/<version> (+https://brw.donworks.co.uk)`.",
      "",
      "Measured 25 September 2026, brw 0.15.2, real signed-in Chromium via the extension bridge, https://revitt.co/book (5 WebMCP tools), reaching a chosen slot with the booking ready to submit, 3 runs each: WebMCP path 3 tool calls, 1.17–1.34 s tool time, 6.7–7.7 KB returned; DOM path 11 tool calls, 0.84–1.32 s, about 55 KB. Tool time is similar; the saving is in agent round trips and bytes read.",
      "",
      "## Recipes",
      "",
      "Since v0.17, run a caller-supplied object with `brw_recipe_run { recipe, inputs }` or a file with `brw run --file .brw/recipes/catalog.1.0.0.json`; no provider or installation is required. Provider recipes retain `brw_recipe_search { query, origin }` followed by `brw_recipe_run { id, version, digest, inputs }`. Both paths validate the recipe and enforce origin, risk and postcondition checks. Inline recipes are not automatically saved or indexed. Recipes are browser mechanics, not standing authorization for an external write.",
      "",
      "Use `.brw/recipes/` as a project convention for reviewed, sanitized files; there is no automatic scan. Validate with `brwctl recipe validate --file <path>`. Keep credentials, account-specific data and raw traces out of committed recipes. Optional HTTP providers can front Maix, Notion or Postgres using adapters you supply; these adapters are not bundled. Guidance: https://github.com/Don-Works/brw/blob/main/docs/repository-recipes.md",
      "",
      "## v0.18 capabilities",
      "",
      "These features require v0.18.0 or newer; check https://github.com/Don-Works/brw/releases/latest before use.",
      "",
      "- Named extraction_json captures select exact sections, uniquely identified tables or allowlisted normalized fields and return bounded artifact handles in outputs. Provenance identifies the source; it does not certify the page is truthful. Section/table selectors reject ambiguous or incomplete sources. Structured captures check expected_source and required normalized fields, without proving that conflicting embedded records agree. Every capture enforces its output budget. Recipes with runtime secrets cannot extract. Contract: https://github.com/Don-Works/brw/blob/main/skills/brw/references/extraction.md",
      "- brw_read accepts settle_ms (0..5000, default 800). After an explicit readiness check, 0 skips the sparse-page wait. CLI: brw read --settle-ms 0. This is a wait budget, not a readiness guarantee.",
      "- Snapshot delta history retains up to eight baselines under a 2 MiB serialized payload budget, with explicit full-snapshot fallback reasons.",
      "- Native WebMCP selects the input representation before one dispatch; errors do not trigger a second invocation. UCP discovery returns bounded declarations, without executing checkout or payment endpoints.",
      "",
      "## Performance evidence",
      "",
      "Historical Apple M4 Max probes from September 2026 measured 2.31x faster pre-armed settling, 51.9x less transfer for a bounded proxied read and a 6,332x smaller response for a 1.31 MB artifact. These measure specific brw operations, not end-to-end competitor or model performance. Methods: https://github.com/Don-Works/brw/blob/82d59b6/docs/benchmarks.md. October measurements and limits: https://github.com/Don-Works/brw/blob/82d59b6/docs/competitive-review-2026-10.md. Wider primary-source research and small-worker/large-planner evaluation design: https://github.com/Don-Works/brw/blob/82d59b6/docs/browser-landscape-2026-10.md. Model routing belongs in the orchestrator; no small-model speed or quality advantage has been established by these probes.",
      "",
      "## Install",
      "",
      "One command on macOS and Linux:",
      "",
      "  curl -fsSL https://brw.donworks.co.uk/install.sh | sh",
      "",
      "It detects the platform, resolves the version, prints its plan, verifies the archive's SHA-256 and its GitHub build-provenance attestation, then installs under `~/Library/Application Support/brw` (macOS) or `~/.local/share/brw` (Linux) with `brwd`, `brwctl`, `brwcheck` and `brw-devtools-mcp` symlinked into `~/.local/bin`. No sudo, nothing outside $HOME. It reads no input. BRW_VERSION, BRW_INSTALL_DIR, BRW_BIN_DIR, BRW_BASE_URL, BRW_NO_SETUP and BRW_SKIP_ATTESTATION change what it does. The script is readable at https://brw.donworks.co.uk/install.sh before it is run.",
      "",
      "It then runs `brwctl setup`, which writes a browser profile policy at ~/Library/Application Support/brw/browser-profiles.json on macOS or ~/.config/brw/browser-profiles.json on Linux, installs a loopback-only background daemon (LaunchAgent on macOS, systemd user unit on Linux, logon task on Windows) bound to 127.0.0.1:17310 and 127.0.0.1:17311, registers brw with Claude Code via `claude mcp add` (`--mcp-client codex` or `both` for Codex, `none` to print the mcpServers block), installs the agent skill into ~/.claude/skills/brw, ~/.agents/skills/brw and ~/.codex/skills/brw, and runs the doctor check. `brwctl setup --dry-run` lists every action without performing one. No step uses sudo.",
      "",
      "Other routes: the macOS .pkg for admin/MDM installs; Linux .deb/.rpm; the Windows .msi. All are on https://github.com/Don-Works/brw/releases.",
      "",
      "Connecting a browser is the one step setup cannot do. Chromium force-installs the extension from a single policy file pointed at the self-hosted CRX and update manifest. Chrome uses load-unpacked today; a Chrome Web Store build is being prepared for review and no listing exists yet. Either way the extension stays disconnected until the user clicks Enable local browser control in its Options page. Extension id: amocjcgddnoakjijfggdpnefdnboilpe.",
      "",
      "Run the daemon directly if you prefer:",
      "",
      "  brwd --mcp --http off",
      "",
      "Or expose the HTTP API on loopback:",
      "",
      "  brwd --http 127.0.0.1:17310",
      "",
      "Source build fallback:",
      "",
      "  git clone https://github.com/Don-Works/brw.git",
      "  cd brw",
      "  make build",
      "  ./bin/brwd --mcp --http off",
      "",
      "Run `brwd --mcp --mcp-tools auto` for the lean default that starts at 14 tools and grows on demand. `core` advertises 26 tools and `minimal` advertises 13; all tools remain callable.",
      "",
      "## Comparison and measurements (checked 1 October 2026)",
      "",
      "These are primary-source feature comparisons and scoped brw measurements, not matched competitor benchmarks. No whole-task speed or success-rate ranking has been established. The installer release at review time is v0.18.1; development optimizations and Python worker experiments are separate.",
      "",
      ...comparisonRows.map((row) => `${row.label}: ${row.strength} brw: ${row.brw} Source: ${row.href}`),
      "",
      ...measurements.map((item) => `${item.status}: ${item.value} ${item.title}. ${item.body}`),
      "",
      "## Transports",
      "",
      "Two lanes, with different capabilities. Extension bridge: drives the user's installed, signed-in Chromium-based browser (Chrome, Chromium, Edge, Brave, Vivaldi, Opera or Arc by name, any other Chromium build via `--browser <name> --user-data-dir <path>`); gets Chrome tab groups; has no incognito, no HttpOnly cookie access and no download routing; started with `brwd --bridge`. Direct CDP: drives a separate browser instance on a profile brw owns; gets incognito contexts (`brw_open_incognito`), cookie tools (`brw_cookies`, HttpOnly included), deterministic download staging and headless; started with `brwd --mcp --http off`. The one-line installer sets up the bridge; `brwctl setup --transport direct-cdp` adds the other lane. `brw_identity` reports which transport a namespace is on.",
      "",
      "## Trust and provenance",
      "",
      "- AGPL-3.0; daemon, CLI and extension in one public repository. The extension ships unminified.",
      "- Every release artifact carries a GitHub build-provenance attestation: `gh attestation verify <artifact> --repo Don-Works/brw` (needs gh 2.49+ and `gh auth login`; the bundle comes from the GitHub API). install.sh performs this check itself before writing anything.",
      "- Every release carries SHA256SUMS.txt and a CycloneDX SBOM (brw_<version>_sbom.cdx.json).",
      "- No release artifact carries a platform code-signing signature: macOS packages are unsigned and not notarised, Windows packages carry no Authenticode signature, and the Linux .deb/.rpm are unsigned with no distribution GPG key. The signing pipeline is written and switches on when certificates are bought; no date is set.",
      "- A release tag builds only after unit tests, a real-browser functional suite, go vet, staticcheck, govulncheck and a gitleaks history scan.",
      "- The extension id amocjcgddnoakjijfggdpnefdnboilpe is pinned by the manifest public key and trusted by the daemon with no configuration.",
      "- Extension privacy policy: https://brw.donworks.co.uk/privacy/extension. The extension collects nothing, transmits nothing to Don Works, Revitt or any third party, and reaches only ws://127.0.0.1 on the user's own machine.",
      "",
      "## Safety",
      "",
      "brw uses a normal visible browser and persistent user profile. It does not add stealth code, CAPTCHA bypass, MFA bypass, fraud-check bypass, or consent bypass. The installed-profile extension refuses HttpOnly cookie and bulk-storage CDP methods; explicit cookie tools exist only on dedicated direct-CDP profiles. Browser-control HTTP binds to loopback by default; for remote use, prefer stdio MCP over SSH.",
      "",
      "Released under AGPL-3.0 — free to use, change, and build on, with improvements shared back. If that doesn't fit your business, ask Revitt about a commercial licence.",
    ].join("\n"),
    {
      headers: {
        "content-type": "text/plain; charset=utf-8",
      },
    },
  );
}
