import {
  agentWebBrwVersion,
  agentWebUpdated,
  aiCatalogExample,
  bookingExampleUrl,
  bookingRows,
  brwAgentGuideUrl,
  brwBookingRunUrl,
  callTimings,
  declarativeFormExample,
  fallbackHints,
  headLinksExample,
  preferenceOrder,
  registerToolExample,
  revittExampleUrl,
  revittSurfaces,
} from "@/lib/agentWeb";

export const dynamic = "force-static";

const fence = (lang: string, body: string) => ["```" + lang, body, "```"].join("\n");

export function GET() {
  const body = [
    "# Sites built for agents take a few calls",
    "",
    `Measured ${agentWebUpdated} with brw ${agentWebBrwVersion}. HTML version: https://brw.donworks.co.uk/agent-web`,
    "",
    "When a site exposes tools, an API or markdown for agents, brw uses them before it drives the page. On a booking site that registers five WebMCP tools, an agent reached a bookable slot in 3 tool calls instead of 11, and read about 7 KB of results instead of about 55 KB.",
    "",
    "## The measured difference",
    "",
    `Target: ${bookingExampleUrl}, driven through the extension bridge in a real signed-in Chromium, three runs per path. The end state for both: a slot is chosen and the booking can be submitted.`,
    "",
    "| Path | Tool calls | Tool time | Returned | What it took |",
    "| --- | ---: | ---: | ---: | --- |",
    ...bookingRows.map(
      (r) => `| ${r.path} | ${r.calls} | ${r.toolTime} | ${r.returned} | ${r.result} |`,
    ),
    "",
    "Tool time is similar on both paths. The saving is in agent round trips, each of which is a model turn, and in the bytes the agent reads, which are tokens.",
    "",
    `Method and raw ranges: ${brwBookingRunUrl}`,
    "",
    "Individual calls:",
    "",
    ...callTimings.map(([call, time]) => `- \`${call}\`: ${time}`),
    "",
    '`brw_read_url` on `github.com/settings/profile` returned `fallback_hint: "login_wall"`.',
    "",
    "## The order brw follows",
    "",
    ...preferenceOrder.map((s) => `${s.order}. **${s.name}.** ${s.body}`),
    "",
    "## What brw does with each surface",
    "",
    "### WebMCP page tools",
    "",
    "- Listed and called on every transport, including the extension bridge in your own signed-in Chrome.",
    "- Native first: when Chrome's own `document.modelContext` is present, brw lists and invokes through it and never shims over it.",
    "- `brwd --enable-webmcp` installs a fallback runtime at document start for browsers without native support, with `navigator.modelContext` as a legacy alias. It is off by default because a page can observe it.",
    "- Declarative `<form toolname>` tools are listed alongside registered ones.",
    "- `readOnlyHint` and `consequentialHint` are surfaced. With confirm-actions on, a consequential tool goes through the same consent gate as a purchase click.",
    "- A tool's result is marked `untrusted_output`: it is data the page wrote, not instructions.",
    "- Tools a site registers after hydration are waited for: `brw_page_tools` waits up to 2 s and `brw_call_page_tool` up to 2.5 s on a young document.",
    "",
    "### On every navigation",
    "",
    "`brw_open`, `brw_navigate_to` and `brw_navigate` report `page_tools` and `agent_surfaces` for the landed page. An ordinary page gets neither field.",
    "",
    "### brw_read_url, with no browser",
    "",
    'No tab and no cookies. It asks for markdown first, then discovers the site\'s agent surfaces: `llms.txt`, `.md` twins, `<link rel="alternate" type="text/markdown">`, the RFC 9727 `/.well-known/api-catalog`, MCP server cards in `/.well-known/ai-catalog.json`, `/.well-known/ucp` and an A2A agent card. An `ai-plugin.json` manifest is reported as deprecated. It echoes `Content-Signal` and `x-markdown-tokens`, and sends an honest user agent: `brw/<version> (+https://brw.donworks.co.uk)`.',
    "",
    "When the read cannot see the page a person would, it says so in `fallback_hint`, and the agent steps up to a real tab:",
    "",
    ...fallbackHints.map(([hint, meaning]) => `- \`${hint}\`: ${meaning}`),
    "",
    `The agent guide has the fields and the exact behaviour: ${brwAgentGuideUrl}`,
    "",
    "## For site owners",
    "",
    `A site brw can use without touching its DOM is one that publishes some of the following. ${revittExampleUrl} publishes all of them and is the live example:`,
    "",
    ...revittSurfaces.map(([label, url]) => `- ${label}: ${url}`),
    "",
    "### Register WebMCP tools",
    "",
    "Call `registerTool(tool, { signal })` on `document.modelContext`. Aborting the signal unregisters the tool, so tie it to the view that owns it. Give each tool an input schema, and set `readOnlyHint` on reads and `consequentialHint` on anything that books, buys or sends.",
    "",
    fence("js", registerToolExample),
    "",
    "### Or declare a form",
    "",
    "A form with a `toolname` is a tool with no script. Without `toolautosubmit`, brw fills it and leaves the submit to the agent once the user has agreed.",
    "",
    fence("html", declarativeFormExample),
    "",
    "### Publish llms.txt and markdown twins",
    "",
    "Write `/llms.txt` to the format at https://llmstxt.org. Publish a markdown copy of each page at its own `.md` URL and link it from the page's head.",
    "",
    fence("html", headLinksExample),
    "",
    "If you also answer `Accept: text/markdown` on the page's own URL: on Vercel with Next.js, the `Vary: Accept` header set by the route did not reach the response, so a browser cache reused the markdown for the HTML URL. Serve Accept-negotiated markdown with `Cache-Control: private, no-store`, or use a separate `.md` URL.",
    "",
    "### Describe your API and MCP server",
    "",
    "Serve an RFC 9727 linkset at `/.well-known/api-catalog` pointing at your OpenAPI description. Serve `/.well-known/ai-catalog.json` with an entry for your MCP server card, so an agent can call the server directly.",
    "",
    fence("json", aiCatalogExample),
    "",
    "### Check what brw sees",
    "",
    "Ask an agent with brw to call `brw_read_url { url }` on one of your pages, and `brw_open` on it. The first reports `agent_surfaces` and any `fallback_hint`; the second reports `page_tools`.",
    "",
  ].join("\n");

  return new Response(body, {
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "x-markdown-tokens": String(Math.ceil(body.length / 4)),
    },
  });
}
